In [1]:
import numpy as np

# Ones vs ones_like

In [9]:
array_1 = np.zeros((10, ))
array_2 = np.ones_like(array_1)
array_3 = np.ones(len(array_1))
print( array_1 )
print( array_2 )
print( array_3 )

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
array_1 = np.ones((10, 1))
array_2 = np.ones((10, 1))
np.dot(array_1.T, array_2)

array([[10.]])

# Get an random matrix

In [23]:
np.random.rand(1, 2, 2)

array([[[0.75014566, 0.39174948],
        [0.84619611, 0.45825522]]])

# 按列数值拆分numpy array

In [2]:
import numpy as np
def split(arr, cond):
    return [arr[cond], arr[~cond]]
arr = np.array([[1,2], [1,4], [1,7], [1,9], [1, 11]])
split(arr, arr[:,1] > 5)

[array([[ 1,  7],
        [ 1,  9],
        [ 1, 11]]), array([[1, 2],
        [1, 4]])]